import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "NexusChat | Real-Time Messaging App",
  description: "Experience seamless real-time communication with NexusChat. Built with Next.js and Socket.io.",
  keywords: ["chat app", "real-time messaging", "Next.js chat", "MERN stack"],
  openGraph: {
    title: "NexusChat",
    description: "Real-time communication made easy.",
    url: "https://your-deployment-url.vercel.app",
    siteName: "NexusChat",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          richColors
          position="top-center"
          closeButton
        />
      </body>
    </html>
  );
}
